"""empty message

Revision ID: 0b37fcb89755
Revises: 
Create Date: 2024-02-23 06:07:17.796640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b37fcb89755'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('title', sa.String(), nullable=False, comment='本の題名'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('name', sa.String(), nullable=False, comment='顧客の名前'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('read_history',
    sa.Column('ncode', sa.String(length=255), nullable=False, comment='小説コード'),
    sa.Column('read_episode', sa.Integer(), nullable=False, comment='既読した話数'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ncode')
    )
    op.create_table('follow',
    sa.Column('read_history_id', sa.Integer(), nullable=False),
    sa.Column('is_follow', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.ForeignKeyConstraint(['read_history_id'], ['read_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    op.drop_table('read_history')
    op.drop_table('customer')
    op.drop_table('book')
    # ### end Alembic commands ###
