"""empty message

Revision ID: 7ab83c34cc54
Revises: b7f87803095f
Create Date: 2024-02-18 06:43:41.544964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ab83c34cc54"
down_revision: Union[str, None] = "b7f87803095f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_ncode", "readhistory", ["ncode"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_ncode", "readhistory", type_="unique")
    # ### end Alembic commands ###
