"""empty message

Revision ID: ae357bab00d5
Revises: d393f331bf5d
Create Date: 2024-03-08 09:19:25.121700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae357bab00d5'
down_revision: Union[str, None] = 'd393f331bf5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('read_history', 'id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('read_history', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('user')
    # ### end Alembic commands ###
