"""empty message

Revision ID: b7f87803095f
Revises: 39377f5a67a1
Create Date: 2024-02-09 17:00:03.395920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b7f87803095f"
down_revision: Union[str, None] = "39377f5a67a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "readhistory",
        sa.Column("ncode", sa.String(), nullable=False, comment="小説コード"),
        sa.Column(
            "read_episode", sa.Integer(), nullable=False, comment="既読した話数"
        ),
        sa.Column("id", sa.String(length=26), nullable=False, comment="ID"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("customer")
    op.drop_table("book")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column(
            "title",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="本の題名",
        ),
        sa.Column(
            "id",
            sa.VARCHAR(length=26),
            autoincrement=False,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="book_pkey"),
    )
    op.create_table(
        "customer",
        sa.Column(
            "name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="顧客の名前",
        ),
        sa.Column(
            "id",
            sa.VARCHAR(length=26),
            autoincrement=False,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "password",
            sa.VARCHAR(length=60),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="customer_pkey"),
    )
    op.drop_table("readhistory")
    # ### end Alembic commands ###
